units:
  px: cx + 8
  py: cy + 8

  pushX: (cx / 2)
  pushY: (cy / 2)

  padX: pushX + 2
  padY: pushY + 2

  pad: 2

  spacing: 0.75

  controllerW: 18.5
  controllerH: 33.5
  belowControllerH: 17
  caseBorder: 1.5
  screwThreadRadius: 0.5
  screwPCBRadius: 4.0

points:
  key:
    padding: cy + spacing
    spread: cx + spacing
  zones:
    matrix:
      columns:
        first:
          key:
            stagger: 0
            column_net: P020 
        second:
          key:
            stagger: 0
            column_net: P022 
        third:
          key:
            stagger: 7
            column_net: P024
        fourth:
          key:
            stagger: 5
            column_net: P100 
        fifth:
          key:
            stagger: -6
            column_net: P011
        sixth:
          key:
            stagger: -3.0
            column_net: P017
      rows:
        # mod:
        #   row_net: P113
        bottom:
          row_net: P115
        home:
          row_net: P002
        top:
          row_net: P029
        num:
          row_net: P031

    thumb:
      anchor:
        ref: matrix_sixth_bottom
        shift: [0, -16]
      columns:
        home:
          key:
            spread: 21.25
            splay: -35
            origin: [-11.75, -9]
            column_net: P006
            row_net: P115  # You can choose an available row net
        far:
          key:
            spread: 21.25
            splay: -28
            origin: [-9.5, -9]
            column_net: P008
            row_net: P115  # Same row net if desired

    #   rows:
    #     thumb:
  # rotate: -5
  mirror:
   ref: matrix_sixth_home
   distance: 80
outlines:
  keys:
    - where: true
      what: rectangle
      size: [14, 14]
      fillet: 6
  board_left:
    - where: true
      what: rectangle
      size: [px, py]
      fillet: 2
  xl_board_left:
    - where: true
      what: rectangle
      size: [px+2, py+2]
      fillet: 2
  board_right:
    - where: true
      what: rectangle
      size: [px, py]
      fillet: 1
  xl_board_key_cutouts:
    - name: xl_board_left
    - operation: subtract
      name: keys

pcbs:
  left:
    outlines:
      main:
        outline: board_left
    footprints:
      choc_hotswap:
        what: choc
        where: /^matrix_.*|^thumb/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
        # Rotate the key switches upside-down (easier to fit controller that way)
          rotate: 180
      # Main diodes
      diode_main:
        what: diode
        where: /^matrix_(?!(?:sixth_top|sixth_home|third_home|first_num|fourth_top|fourth_mod|first_home)).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, -3.5]
          rotate: 90
      # Thumb diodes
      diode_thumb:
        what: diode
        where: /^thumb_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, -3.5]
          rotate: 90
      diode_weird1:
        what: diode
        where: matrix_sixth_top
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, -16.0]
          rotate: 90
      # Move another diode so it doesn't conflict with controller
      diode_weird2:
        what: diode
        where: matrix_sixth_home
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, -9.5]
          rotate: 90

      diode_mounting_hole_conflict1:
        what: diode
        where: /^matrix_(?:third_home|first_num|first_home)/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, 3.5]
          rotate: 90
      diode_mounting_hole_conflict2:
        what: diode
        where: /^matrix_(?:fourth_top|fourth_mod)/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, -4.5]
          rotate: 90
      # # Battery jack
      jstph:
        what: jstph
        where:
          ref: matrix_fourth_home
          shift: [-7, 5.5]
          rotate: 90
        params:
            side: B
            pos: pos
            neg: GND

      # Reset switch (horizontal community version)
      # this switch footprint does not work with kicad (added manually)
      horizontal_reset:
       what: EVQPUC
       params: 
         side: B
         from: GND
         to: RST 
       where:
         ref: matrix_sixth_top
         shift: [9.0, 2.8]
         rotate: -90.0
          
      # Battery on/off switch
      battery_switch:
        what: slider
        where:
            ref: matrix_sixth_top
            shift: [10.8, -6.0]
            rotate: -90
        params:
            side: B
            from: pos
            to: RAW


      # Mounting holes
      hole_bottom_right:
        what: mountinghole
        where:
          ref: matrix_sixth_bottom
          shift: [-pushX, pushY]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: matrix_first_home
          shift: [pushX, -pushY]
      hole_top_left:
        what: mountinghole
        where:
          ref: matrix_second_num
          shift: [-pushX, -pushY]
      hole_top_right:
        what: mountinghole
        where:
          ref: matrix_fifth_top
          shift: [-pushX, pushY]
      # hole_center:
      #   what: mountinghole
      #   where:
      #     ref: matrix_fourth_bottom
      #     shift: [-pushX, pushY]


      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: matrix_sixth_num
          shift: [-9, -1.5]
          rotate: -180.0

  right:
    outlines:
      main:
        outline: board_right
    footprints:
      choc_hotswap:
        what: choc
        where: /^mirror_matrix_(?!(?:sixth_top)).*|mirror_thumb/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
        # Rotate the key switches upside-down (easier to fit controller that way)
          rotate: 180
      # Main diodes
      choc_hotswap_conflict:
        what: choc 
        where: mirror_matrix_sixth_top
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: 90

      diode_main:
        what: diode
        #where: /^mirror_matrix_(?!(?:sixth_top|sixth_home|third_home|first_num|fourth_top|fourth_mod|first_home)).*/
        where: /^mirror_matrix_(?!(?:sixth_num|sixth_top|fifth_num|fifth_top)).*|mirror_thumb/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-3, 5]
          rotate: 180
      # Thumb diodes
      # diode_thumb:
      #   what: diode
      #   where: /^mirror_thumb_.*/
      #   params:
      #     from: "{{colrow}}"
      #     to: "{{row_net}}"
      #   adjust:
      #     shift: [7.8, -3.5]
      #     rotate: 90
      diode_weird1:
        what: diode
        where: mirror_matrix_sixth_num
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-8, -2]
          rotate: 90
      # Move another diode so it doesn't conflict with controller
      diode_weird2:
        what: diode
        where: mirror_matrix_fifth_num
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, 7]
          rotate: 0

      diode_weird3:
        what: diode
        where: mirror_matrix_fifth_top
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-7.7, -2]
          rotate: 90
      diode_weird4:
        what: diode
        where: mirror_matrix_sixth_top
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [5, 0]
          rotate: 90

      # diode_mounting_hole_conflict1:
      #   what: diode
      #   where: /^mirror_matrix_(?:third_home|first_num|first_home)/
      #   params:
      #     from: "{{colrow}}"
      #     to: "{{row_net}}"
      #   adjust:
      #     shift: [7.8, 3.5]
      #     rotate: 90
      # diode_mounting_hole_conflict2:
      #   what: diode
      #   where: /^mirror_matrix_(?:fourth_top|fourth_mod)/
      #   params:
      #     from: "{{colrow}}"
      #     to: "{{row_net}}"
      #   adjust:
      #     shift: [7.8, -4.5]
      #     rotate: 90

      # # Battery jack
      jstph:
        what: jstph
        where:
          ref: mirror_matrix_fourth_home
          shift: [-10, 0]
          rotate: -90
        params:
            side: B
            pos: pos
            neg: GND

      # Reset switch (horizontal community version)
      # this switch footprint does not work with kicad (added manually)
      horizontal_reset:
       what: EVQPUC
       params: 
         side: B
         from: GND
         to: RST 
       where:
         ref: mirror_matrix_sixth_top
         shift: [11.0, 2.8]
         rotate: -90.0
          
      # Battery on/off switch
      battery_switch:
        what: slider
        where:
            ref: mirror_matrix_sixth_top
            shift: [10.8, -6.0]
            rotate: -90
        params:
            side: B
            from: pos
            to: RAW


      # Mounting holes
      hole_bottom_right:
        what: mountinghole
        where:
          ref: mirror_matrix_sixth_bottom
          shift: [-pushX, pushY]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: mirror_matrix_first_home
          shift: [pushX, -pushY]
      hole_top_left:
        what: mountinghole
        where:
          ref: mirror_matrix_second_num
          shift: [-pushX, -pushY]
      hole_top_right:
        what: mountinghole
        where:
          ref: mirror_matrix_fifth_top
          shift: [-pushX, pushY]
      # hole_center:
      #   what: mountinghole
      #   where:
      #     ref: mirror_matrix_fourth_bottom
      #     shift: [-pushX, pushY]


      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: mirror_matrix_sixth_num
          shift: [-9, -1.5]
          rotate: 0.0



cases:
  plate:
    - name: xl_board_key_cutouts
      extrude: 1.2

